[tool.poetry]
name = "misskist"
version = "0.1.0"
description = ""
authors = ["tuna2134 <me@tuna2134.dev>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
aiohttp = "^3.8.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
